FROM python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV USING_GPU 0

WORKDIR /app

RUN apt update
RUN apt install -y gcc-11
RUN apt install -y g++-11
RUN CXX=g++-11 CC=gcc-11 pip install llama-index-llms-llama-cpp --upgrade --force-reinstall --no-cache-dir

COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt


COPY . /app/ 
RUN mkdir /app/models
RUN mkdir /app/vector_db_store


# CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8001"]
CMD ["/bin/bash"]